version: '3.8'

services:
    backend:
        build:
            context: ..
            dockerfile: Dockerfile
        container_name: backend
        ports:
            - '3000:3000'
        env_file:
            - ../.env
        depends_on:
            - db
        restart: on-failure:10
        networks:
            - homework-network
    db:
        image: mysql:latest
        container_name: database
        ports:
            - '3306:3306'
        command: --sql_mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
        environment:
            - MYSQL_ROOT_PASSWORD=test
            - MYSQL_DATABASE=test
        volumes:
            - ./mysql-db:/var/lib/mysql
        restart: on-failure
        networks:
            - homework-network

networks:
    homework-network:
        driver: bridge
